django/api/urls.py
from api.resources import CategoryResource, CourseResource
from django.urls import include, path
from tastypie.api import Api

api = Api(api_name='v1')
api.register(CategoryResource())
api.register(CourseResource())

# /api/v1/categories/   GET
# /api/v1/categories/1/ GET
# /api/v1/courses/      GET, POST
# /api/v1/courses/1/    GET, DELETE

# Для методов POST и DELETE требуется авторизация с помощью ключа API.
# Ключ заголовка: Authorization
# Значение заголовка: ApiKey <username>:<api_key>

urlpatterns = [
    path('', include(api.urls), name='root')
]

django/base/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls'))
]

django/shop/urls.py
from . import views
from django.urls import path

app_name = 'shop'

urlpatterns = [
    # Список всех курсов.
    path('', views.courses, name='index'),
    # Страница отдельного курса.
    path('course/<int:course_id>', views.single_course, name='single_course')
]

django/shop/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):

    class Meta:

        verbose_name = 'category'

        verbose_name_plural = 'categories'

    created_at = models.DateTimeField(default=timezone.now)

    title = models.CharField(max_length=128)

    def __str__(self):
        return self.title


class Course(models.Model):

    class Meta:

        verbose_name = 'course'

        verbose_name_plural = 'courses'

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    created_at = models.DateTimeField(default=timezone.now)

    price = models.FloatField()

    review_quantity = models.IntegerField()

    student_quantity = models.IntegerField()

    title = models.CharField(max_length=256)

    def __str__(self):
        return self.title

django/shop/views.py
from .models import Course
# from django.http import Http404
from django.shortcuts import get_object_or_404, render


def courses(request):
    courses = Course.objects.all()
    return render(
        request=request,
        template_name='shop/courses.html',
        context={'courses': courses}
    )


def single_course(request, course_id):
    # Вариант 1

    # try:
    #     course = Course.objects.get(pk=course_id)
    #     return render(
    #         request=request,
    #         template_name='shop/single_course.html',
    #         context={'course': course}
    #     )
    # except Course.DoesNotExist:
    #     raise Http404()

    # Вариант 2

    course = get_object_or_404(Course, pk=course_id)
    return render(
        request=request,
        template_name='shop/single_course.html',
        context={'course': course}
    )

django/templates/base.html
<!DOCTYPE html>

<html lang="ru">

<meta charset="utf-8">
<meta name="description" content="Полный курс по Python Богдана Стащука">
<meta name="viewport" content="initial-scale=1.0, width=device-width">

<title>{% block title %}{% endblock %}</title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<nav class="bg-dark navbar navbar-dark">
	<div class="container">
		<a href="{% url 'shop:index' %}" class="navbar-brand">Магазин курсов</a>
		<span>
			<a href="{% url 'admin:index' %}" class="navbar-brand">Панель администратора</a>
			<a href="/api/v1/" class="navbar-brand">Сервис API</a>
		</span>
	</div>
</nav>

<main class="container">
	{% block content %}
	{% endblock %}
</main>

</html>

django/templates/shop/courses.html
{% extends 'base.html' %}

{% block title %}Все курсы{% endblock %}

{% block content %}
<table class="table table-bordered table-hover table-striped mt-3">
	<thead class="table-dark">
		<tr>
			<th>Название</th>
			<th>Категория</th>
			<th>Цена</th>
			<th>Количество студентов</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		{% for course in courses %}
		<tr>
			<td>
				<a href="{% url 'shop:single_course' course.id %}">{{ course.title }}</a>
			</td>
			<td>{{ course.category }}</td>
			<td>{{ course.price }}</td>
			<td>{{ course.student_quantity }}</td>
			<td>
				<button class="btn btn-primary">Купить</button>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

django/templates/shop/single_course.html
{% extends 'base.html' %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
<h1>{{ course.title }}</h1>
<h2>{{ course.category }}</h2>
<p>Цена: {{ course.price }}</p>
<p>Студентов: {{ course.student_quantity }}</p>
<p>Отзывов: {{ course.review_quantity }}</p>
<button class="btn btn-primary">Купить</button>
{% endblock %}